### ISSUE TITLE
Modderation: Permabanned Mod Updates for 1.1.2

### ISSUE THREAD

**Issue by sandalle** [mechaet/ModderationConfigs#13]
[Modderation: Permabanned Mod Updates for 1.1.2](https://www.evernote.com/shard/s245/sh/addfbe2e-e727-48f0-8fa7-af32dec1c8ea/8665a9ba044d94bf2f71acef8adabb5b).

@sandalle needs to provide updated configs in a Pull request. :)

**Comment by sandalle** [comment]
The Secret Doors Mod update ( https://github.com/AbrarSyed/SecretRoomsMod-forge/commit/2e1d39c4e050e8f2078596cd3b19f9cfd7d43f62 ) is supposedly included in this roll-up.

**Comment by sandalle** [comment]
For [Mekanism](http://aidancbrady.com/mekanism/) v8 ([general changes](http://aidancbrady.com/2015/03/its-that-time-of-the-week/)), There has been [success reported on upgrading existing worlds with Mekanism 7](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284681-mekanism-v8-0-2-fusion-reactors-5x-ore-duplication?page=82#c1647), but may be [broken with Thaumic Energistics](https://github.com/Nividica/ThaumicEnergistics/issues/147) ([really AE2 bug](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061)).
We may want to pass on Mekanism v8 update until next update cycle.

**Comment by sandalle** [comment]
Mekanism v8 [reportedly works with Applied Energistics 2 rv2-beta-18](https://github.com/Nividica/ThaumicEnergistics/issues/147#issuecomment-86784548) now. :)

**Comment by sandalle** [comment]
After updating locally on client and server, I do see this:

```
[17:32:14 WARN]: Forge Mod Loader detected missing blocks/items.

There are 2 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
chisel:stonebricksmooth2
chisel:stonebricksmooth2


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

**Comment by sandalle** [comment]
I believe you said Mekanism v8 will be in the next release, so I have _not_ downloaded and updated that. :)

**Comment by sandalle** [comment]
Apparently my fork isn't kept in-sync even after a merge, so I need to do https://help.github.com/articles/syncing-a-fork/ and re-do my current commits. :) Working through the 1.1.2 updates as listed in the original post (no additions since then).

**Comment by sandalle** [comment]
There is another [release version of Thermal Dynamics](http://minecraft.curseforge.com/mc-mods/227443-thermal-dynamics/files/2232253), but it is not included in this round of updates. I have 14 other updates for the next round that I haven't looked at yet (e.g. to check the changes).

**Comment by sandalle** [comment]
This will now include the updated Thermal Dynamics release. :)

**Comment by sandalle** [comment]
Pull Request #15 has been merged into master.

**Comment by sandalle** [comment]
The updates above work on my client and server, though it is far simpler (less magic and technology deployed in the world) with fewer users. :)

**Comment by sandalle** [comment]
@mechaet , I have about 37 more mod updates, including most of the CoFH mods having a stable release, in my updates folder that I can parse through and add to [Modderation: Permabanned Mod Updates for 1.1.2](https://www.evernote.com/shard/s245/sh/addfbe2e-e727-48f0-8fa7-af32dec1c8ea/8665a9ba044d94bf2f71acef8adabb5b) if you want for 1.1.2, or I can queue them for 1.1.3.

**Comment by mechaet** [comment]
Put them in 1.1.2

Sent from my Windows Phone

**Comment by sandalle** [comment]
1.1.2b updates added to [Modderation: Permabanned Mod Updates for 1.1.2](https://www.evernote.com/shard/s245/sh/addfbe2e-e727-48f0-8fa7-af32dec1c8ea/8665a9ba044d94bf2f71acef8adabb5b) in blue, now I just need to update the configuration files, which is unlikely until Thursday, depending on how work goes.

**Comment by sandalle** [comment]
Config and mod changes for 1.1.2b request have some more block changes.

```
[15:17:35 WARN]: Forge Mod Loader detected missing blocks/items.

There are 3 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
technom:pureYellorium
chisel:stonebricksmooth2
chisel:stonebricksmooth2


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

Configuration files merged into master with Pull #17 .

**Comment by Carbon-Ghost** [comment]
Hi, just wanted to report that Mekanism crashes again with Thaumic AE, with the newest stable version of both mods :C

**Comment by sandalle** [comment]
@Carbon-Ghost , please open a new Issue to track this, unless you mean the versions posted in this thread? Please always include the mod versions, just to avoid ambiguity. :) I only tested a basic world with not much built-up. :)

**Comment by Carbon-Ghost** [comment]
Nvm the crash for now, it's already outdated ^.^

**Comment by sandalle** [comment]
[Modderation Updates for 1.1.2c](https://www.evernote.com/shard/s245/sh/addfbe2e-e727-48f0-8fa7-af32dec1c8ea/8665a9ba044d94bf2f71acef8adabb5b) has the 1.1.2c updates in purple, including an update to Forge 10.13.3.1408 (with matching Cauldron update) and the Bukkit plug-in updates. Everything seems to work on my test server with mostly magic, lots of exploration, and some technology (TE and Mekanism basic machines/power for testing) setup.

**Comment by sandalle** [comment]
[Modderation Updates for 1.1.2c](https://www.evernote.com/shard/s245/sh/addfbe2e-e727-48f0-8fa7-af32dec1c8ea/8665a9ba044d94bf2f71acef8adabb5b) and Pull Request #19 have the 1.1.2c updates in purple, including an update to Forge 10.13.3.1408 (with matching Cauldron update) and the Bukkit plug-in updates. Everything seems to work on my test server with mostly magic, lots of exploration, and some technology (TE and Mekanism basic machines/power for testing) setup.

This update has the following changed/modified blocks

```
There are 12 missing blocks and items in this save.
If you continue the missing blocks/items will get removed.
A world backup will be automatically created in your saves directory.

Missing Blocks/Items:
technom:reconstructorBlock
technom:pureYellorium
technom:reconstructorBlock
AWWayofTime:itemMailCatalogue
simplyjetpacks:fluxpacksEIO
simplyjetpacks:jetpacksEIO
chisel:stonebricksmooth2
chisel:stonebricksmooth2
factorization:ColossalBlock
factorization:twistedBlock
factorization:ColossalBlock
factorization:colossusGuide


Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

**Comment by sandalle** [comment]
See https://github.com/Chisel-2/Chisel-2/issues/261 for chisel:stonebricksmooth2 missing block (removed from mod).

**Comment by sandalle** [comment]
1.1.2c is out to both client and server, but are affected by https://github.com/rwtema/extrautilities/issues/620 until [Extra Utilities](http://minecraft.curseforge.com/mc-mods/225561-extra-utilities) is updated (currently 1.2.5).
