### ISSUE TITLE
MineFactory Reloaded (MFR) recipes do not function in NEI or in-game

### ISSUE THREAD

**Issue by sandalle** [mechaet/ModderationConfigs#7]
Bluemillion reported this.

From commit 83ff516436e1b7c7d9b43631d6e09261f5b724a5 (my bad), all MFR recipes were disabled (apparently that's the default setting?).

Both client (so NEI won't show the recipes and crafting tables won't show valid output, but you can craft it if the server knows of it) and server (so even with knowing the recipes, they can't be crafted) have EnderIO, Thermal Expansion, and Vanilla recipes disabled.

**Comment by sandalle** [comment]
Requires both the server and client to be updated.

**Comment by sandalle** [comment]
Server-side is currently fixed so they can be crafted if you know the recipe, but unless you apply the config to your clients you won't see the recipes in NEI nor will you see the output when crafting, but click the "empty" output to grab the item until the client is updated.

**Comment by mechaet** [comment]
I'll be pushing this config change to the client pack once I have some mods to add and/or update.
